# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit Tests

on:
    # Only for PR against master branch
    pull_request:
        branches: [master]

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node_version:
                    - 12
                    - 14
                    - 15

        name: Node ${{ matrix.node_version }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm test
